name: flutter_open_project
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^3.7.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.3.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  google_sign_in: ^5.4.4
  google_fonts: ^4.0.1
  freezed_annotation: ^2.2.0
  flutter_gallery_assets: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  build_runner: ^2.3.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Thin.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-SemiBold.ttf